name: "🐛 Bug report"
description: Report errors or unexpected behavior
labels: 
- bug
body:
- type: markdown
  attributes:
    value: |
      Please make sure to [search for existing issues](https://github.com/dragonofmercy/Dragon-Better-History/issues) before filing a new one!

- type: textarea
  attributes:
    label: Steps to reproduce
    description: We highly suggest including screenshots or code sample.
    placeholder: Tell us the steps required to trigger your bug.
  validations:
    required: true

- type: textarea
  attributes:
    label: ✔️ Expected Behavior
    placeholder: What were you expecting?
  validations:
    required: false

- type: textarea
  attributes:
    label: ❌ Actual Behavior
    placeholder: What happened instead?
  validations:
    required: false

- type: textarea
  attributes:
    label: Bowser informations
    description: please complete the following information
    placeholder: |
      OS: [e.g. iOS]
      Browser [e.g. chrome, safari]
      Version [e.g. 22]
  validations:
    required: false
